DROP TABLE IF EXISTS person;

CREATE TABLE Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar NOT NULL ,
                       surname varchar NOT NULL ,
                       age int CHECK ( age > 0 ),
                       email varchar UNIQUE
);

INSERT INTO person (name, surname, age, email, address) VALUES
                                                   ('Tom','Smith', 18, 'email@eamil.com', 'Ukraine, Odessa, 123456'),
                                                   ('Sem','Ymith', 18, 'email1@eamil.com', 'Ukraine, Kyiv, 654321'),
                                                   ('Nil','Mith', 18, 'email3@eamil.com', 'Italy, Rome, 321456'),
                                                   ('Nick','Smith', 28, 'email2@eamil.com', 'America, Texas, 987654');
