DROP TABLE IF EXISTS person;

CREATE TABLE Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar NOT NULL ,
                       surname varchar NOT NULL ,
                       age int CHECK ( age > 0 ),
                       email varchar UNIQUE
);

INSERT INTO person (name, surname, age, email) VALUES
                                                   ('Tom','Smith', 18, 'email@eamil.com'),
                                                   ('Sem','Ymith', 18, 'email1@eamil.com'),
                                                   ('Nil','Mith', 18, 'email3@eamil.com'),
                                                   ('Nick','Smith', 28, 'email2@eamil.com');
